### ISSUE TITLE
Create repositories for rpi images

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/provider-kubeadm#22]
We need following docker image repositories for building the rpi based images

core-opensuse-arm-rpi-kubeadm
core-ubuntu-20-lts-arm-rpi-kubeadm
core-ubuntu-22-lts-arm-rpi-kubeadm

**Comment by mauromorales** [comment]
Created the empty repos in quay:

- https://quay.io/repository/kairos/core-opensuse-arm-rpi-kubeadm
- https://quay.io/repository/kairos/core-ubuntu-20-lts-arm-rpi-kubeadm
- https://quay.io/repository/kairos/core-ubuntu-22-lts-arm-rpi-kubeadm

Let me know if it's working

**Comment by jimmykarily** [comment]
Closing as done. @venkatnsrinivasan please open again if something is not right.
